services:
  - type: web
    name: greensnap-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: vmongodb+srv://waste_app_user:waste123@cluster0.dmhyjdx.mongodb.net/user_db?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 15d
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_MAIL
        value: greensnapofficial@gmail.com
      - key: SMTP_PASSWORD
        value: fwau tsns hxzl mqif
      - key: COOKIE_EXPIRE
        value: 7